package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestParse(t *testing.T) {
	assert := assert.New(t)
	start, rows := parseInput(example)

	assert.Equal(7, start)
	assert.Equal(splitterRow{}, rows[0])
	assert.Equal(splitterRow{7}, rows[1])
	assert.Equal(splitterRow{}, rows[2])
	assert.Equal(splitterRow{6, 8}, rows[3])

}
